from backend.app.repositories.in_memory import (
    InMemoryArtifactRepository,
    InMemorySessionRepository,
    InMemoryTaskRepository,
    InMemoryUploadedFileRepository,
)
from backend.app.repositories.postgres import (
    PostgresArtifactRepository,
    PostgresArtifactSourceRepository,
    PostgresDerivedContentRepository,
    PostgresDocumentRepository,
    PostgresDocumentVersionRepository,
    PostgresPresentationRepository,
    PostgresPresentationVersionRepository,
    PostgresSessionRepository,
    PostgresStoredFileRepository,
    PostgresTaskRepository,
    PostgresUploadedFileRepository,
)
from backend.app.repositories.interfaces import (
    ArtifactRepository,
    ArtifactSourceRepository,
    DerivedContentRepository,
    DocumentRepository,
    DocumentVersionRepository,
    PresentationRepository,
    PresentationVersionRepository,
    SessionRepository,
    StoredFileRepository,
    TaskRepository,
    UploadedFileRepository,
)
from backend.app.repositories.sqlite import (
    SqliteArtifactRepository,
    SqliteSessionRepository,
    SqliteTaskRepository,
    SqliteUploadedFileRepository,
)
from backend.app.repositories.storage import FileStorage

__all__ = [
    "ArtifactRepository",
    "ArtifactSourceRepository",
    "DerivedContentRepository",
    "DocumentRepository",
    "DocumentVersionRepository",
    "FileStorage",
    "InMemoryArtifactRepository",
    "InMemorySessionRepository",
    "InMemoryTaskRepository",
    "InMemoryUploadedFileRepository",
    "PostgresArtifactRepository",
    "PostgresArtifactSourceRepository",
    "PostgresDerivedContentRepository",
    "PostgresDocumentRepository",
    "PostgresDocumentVersionRepository",
    "PostgresPresentationRepository",
    "PostgresPresentationVersionRepository",
    "PostgresSessionRepository",
    "PostgresStoredFileRepository",
    "PostgresTaskRepository",
    "PostgresUploadedFileRepository",
    "PresentationRepository",
    "PresentationVersionRepository",
    "SessionRepository",
    "SqliteArtifactRepository",
    "SqliteSessionRepository",
    "SqliteTaskRepository",
    "SqliteUploadedFileRepository",
    "StoredFileRepository",
    "TaskRepository",
    "UploadedFileRepository",
]
