from __future__ import annotations

from typing import Protocol

from backend.app.domain import (
    Artifact,
    ArtifactSource,
    DerivedContent,
    Document,
    DocumentVersion,
    ExecutionRun,
    Presentation,
    PresentationVersion,
    Session,
    StoredFile,
    Task,
    UploadedFile,
)


class SessionRepository(Protocol):
    def create(self, session: Session) -> Session: ...

    def get(self, session_id: str) -> Session | None: ...


class TaskRepository(Protocol):
    def create(self, task: Task) -> Task: ...

    def update(self, task: Task) -> Task: ...

    def get(self, task_id: str) -> Task | None: ...

    def list_by_session(self, session_id: str) -> list[Task]: ...


class ArtifactRepository(Protocol):
    def create(self, artifact: Artifact) -> Artifact: ...

    def get(self, artifact_id: str) -> Artifact | None: ...

    def list_by_session(self, session_id: str) -> list[Artifact]: ...


class UploadedFileRepository(Protocol):
    def create(self, uploaded_file: UploadedFile) -> UploadedFile: ...

    def get(self, file_id: str) -> UploadedFile | None: ...

    def list_by_session(self, session_id: str) -> list[UploadedFile]: ...


class StoredFileRepository(Protocol):
    def create(self, stored_file: StoredFile) -> StoredFile: ...

    def get(self, stored_file_id: str) -> StoredFile | None: ...

    def list_by_session(self, session_id: str) -> list[StoredFile]: ...


class DocumentRepository(Protocol):
    def create(self, document: Document) -> Document: ...

    def get(self, document_id: str) -> Document | None: ...

    def list_by_session(self, session_id: str) -> list[Document]: ...


class DocumentVersionRepository(Protocol):
    def create(self, document_version: DocumentVersion) -> DocumentVersion: ...

    def list_by_document(self, document_id: str) -> list[DocumentVersion]: ...


class PresentationRepository(Protocol):
    def create(self, presentation: Presentation) -> Presentation: ...

    def get(self, presentation_id: str) -> Presentation | None: ...

    def list_by_session(self, session_id: str) -> list[Presentation]: ...


class PresentationVersionRepository(Protocol):
    def create(self, presentation_version: PresentationVersion) -> PresentationVersion: ...

    def list_by_presentation(self, presentation_id: str) -> list[PresentationVersion]: ...


class ArtifactSourceRepository(Protocol):
    def create(self, artifact_source: ArtifactSource) -> ArtifactSource: ...

    def list_by_artifact(self, artifact_id: str) -> list[ArtifactSource]: ...


class DerivedContentRepository(Protocol):
    def create(self, derived_content: DerivedContent) -> DerivedContent: ...

    def list_by_file(self, file_id: str) -> list[DerivedContent]: ...



class ExecutionRunRepository(Protocol):
    def create(self, execution_run: ExecutionRun) -> ExecutionRun: ...

    def update(self, execution_run: ExecutionRun) -> ExecutionRun: ...

    def get(self, execution_run_id: str) -> ExecutionRun | None: ...

    def list_by_task(self, task_id: str) -> list[ExecutionRun]: ...
