from __future__ import annotations

from typing import Protocol


class FileStorage(Protocol):
    backend_name: str

    def save_bytes(self, *, storage_key: str, content: bytes, content_type: str | None = None) -> str: ...

    def read_bytes(self, *, storage_key: str) -> bytes: ...

    def exists(self, *, storage_key: str) -> bool: ...

    def delete(self, *, storage_key: str) -> None: ...

    def get_size(self, *, storage_key: str) -> int | None: ...

    def make_uri(self, *, storage_key: str) -> str: ...
